using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace StudentApi.Model
{
    public class StudentData
    {
        [BsonId]
        public ObjectId InternalId { get; set; }                // standard BSonId generated by MongoDb
        public string StudentId { get; set; }                          // external Id, easier to reference: 1,2,3 etc. 
        public string FirstName { get; set; } = string.Empty;    
        public string LastName { get; set; } = string.Empty;     
        public int Age { get; set; }
        public string Grade { get; set; } = string.Empty;
        public string Gender { get; set; } = string.Empty;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }
}
